version: '3.8'

services:
  app:
    build: .
    container_name: stockflow ##nome do contêiner
    ports:
      - "8000:80"  ## Acessa o site pela porta 8000
    volumes:
      - .:/var/www/html  ## Monta a pasta do projeto no contêiner
    depends_on:
      - db  ## Dependência do contêiner db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockflow
    volumes:
      - ./database:/var/lib/mysql ## Monta a pasta do banco de dados no contêiner
    ports:
      - "3306:3306"  ## MySQL 3306 no host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"  ## Porta phpMyAdmin